name: CI Run build and test

on:
  push:

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build with Maven
        run: mvn install
      -
        name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: bonus-demo:latest